sylius_twig_hooks:
    hooks:
        'sylius_shop.order.thank_you.content':
            header:
                enabled: false
            payment_instruction:
                enabled: false
            booking_banner:
                template: 'shop/order/thank_you/booking_banner.html.twig'
                priority: 200
            booking_details:
                template: 'shop/order/thank_you/booking_details.html.twig'
                priority: 150

        'sylius_shop.product.show.content.info.summary':
            interest_button:
                template: 'shop/product/show/interest_button.html.twig'
                priority: 50

        'sylius_shop.account.interests.index.content':
            menu:
                template: '@SyliusShop/account/common/content/menu.html.twig'
                priority: 100
            main:
                template: 'shop/account/interests/main.html.twig'
                priority: 0
