imports:
    - { resource: "../vendor/sylius/sylius/src/Sylius/Behat/Resources/config/services.xml" }

sylius_api:
    enabled: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    App\Tests\Behat\:
        resource: '../tests/Behat/'
